version: '3'
services:
  mysqldb:
    image: mysql
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always  # si muere, va a intentar levantar de nuevo
    environment:
      #credenciales
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datab
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
    ports:
      - "3600:3306" #pc/contenedor
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  servidor:
    build: 
      context: ./Backend/Servidor  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "50051:50051"
    volumes:
      - ./Backend/Servidor:/Servidor
    restart: always
    depends_on:
      - mysqldb
